Repository charmdong/account-book, pull requests merged in 2021-11, with the labels that each got.

#1 UserAndCategory Pull Request
  src/main/java/com/accountbook/api/UserApiController.java
  src/main/java/com/accountbook/api/UserCategoryApiController.java
  src/main/java/com/accountbook/domain/entity/Category.java
  src/main/java/com/accountbook/domain/entity/User.java
  src/main/java/com/accountbook/domain/entity/UserCategory.java
  src/main/java/com/accountbook/domain/repository/CategoryRepository.java
  src/main/java/com/accountbook/domain/repository/UserCategoryRepository.java
  src/main/java/com/accountbook/domain/repository/UserRepository.java
  src/main/java/com/accountbook/domain/repository/UserRepositoryCustom.java
  src/main/java/com/accountbook/domain/repository/UserRepositoryCustomImpl.java
  src/main/java/com/accountbook/dto/user/CategoryRequest.java
  src/main/java/com/accountbook/dto/user/UserCategoryDto.java
  src/main/java/com/accountbook/dto/user/UserDto.java
  src/main/java/com/accountbook/dto/user/UserRequest.java
  src/main/java/com/accountbook/service/UserCategoryService.java
  src/main/java/com/accountbook/service/UserService.java
Labels: DONGGUN

#2 Budget 서비스 개발
  src/main/java/com/accountbook/api/BudgetController.java
  src/main/java/com/accountbook/domain/entity/Budget.java
  src/main/java/com/accountbook/domain/enums/PeriodType.java
  src/main/java/com/accountbook/domain/repository/BudgetRepository.java
  src/main/java/com/accountbook/dto/Budget/BudgetDto.java
  src/main/java/com/accountbook/dto/Budget/BudgetRequest.java
  src/main/java/com/accountbook/service/BudgetService.java
Labels: SOOMIN

#3 Mg asset
  src/main/java/com/accountbook/api/AssetApiController.java
  src/main/java/com/accountbook/domain/entity/Asset.java
  src/main/java/com/accountbook/domain/entity/CreditAsset.java
  src/main/java/com/accountbook/domain/entity/GeneralAsset.java
  src/main/java/com/accountbook/domain/enums/AssetType.java
  src/main/java/com/accountbook/domain/repository/AssetRepository.java
  src/main/java/com/accountbook/dto/AssetDto.java
  src/main/java/com/accountbook/dto/AssetRequest.java
  src/main/java/com/accountbook/service/AssetService.java
Labels: MINGEON

#4 Budget 서비스 테스트 코드, EcoEvent 서비스 개발
  src/main/java/com/accountbook/api/BudgetApiController.java
  src/main/java/com/accountbook/api/EcoEventApiController.java
  src/main/java/com/accountbook/domain/entity/EcoEvent.java
  src/main/java/com/accountbook/domain/repository/BudgetRepository.java
  src/main/java/com/accountbook/domain/repository/EcoEventRepository.java
  src/main/java/com/accountbook/dto/EcoEvent/EcoEventDto.java
  src/main/java/com/accountbook/dto/EcoEvent/EcoEventRequest.java
  src/main/java/com/accountbook/service/BudgetService.java
  src/main/java/com/accountbook/service/EcoEventService.java
  src/test/java/com/accountbook/service/BudgetServiceTest.java
Labels: SOOMIN

#7 Mg asset
  src/main/java/com/accountbook/domain/entity/Asset.java
  src/main/java/com/accountbook/domain/repository/AssetRepository.java
  src/main/java/com/accountbook/domain/repository/AssetRepositoryCustom.java
  src/main/java/com/accountbook/domain/repository/AssetRepositoryCustomImpl.java
  src/main/java/com/accountbook/domain/repository/UserRepositoryCustom.java
  src/main/java/com/accountbook/dto/AssetRequest.java
  src/main/java/com/accountbook/service/AssetService.java
  src/main/resources/application.yml
  src/test/java/com/accountbook/domain/repository/AssetRepositoryTest.java
  src/test/java/com/accountbook/service/AssetServiceTest.java
Labels: MINGEON

#6 Pull Request [DG_userAndCategory]
  build.gradle
  src/main/java/com/accountbook/api/CategoryApiController.java
  src/main/java/com/accountbook/api/UserApiController.java
  src/main/java/com/accountbook/domain/entity/Category.java
  src/main/java/com/accountbook/domain/entity/ComCategory.java
  src/main/java/com/accountbook/domain/entity/User.java
  src/main/java/com/accountbook/domain/enums/EventType.java
  src/main/java/com/accountbook/domain/repository/CategoryRepository.java
  src/main/java/com/accountbook/domain/repository/category/CategoryRepository.java
  src/main/java/com/accountbook/domain/repository/category/ComCategoryRepository.java
  src/main/java/com/accountbook/domain/repository/user/UserRepository.java
  src/main/java/com/accountbook/domain/repository/user/UserRepositoryCustom.java
  src/main/java/com/accountbook/domain/repository/user/UserRepositoryCustomImpl.java
  src/main/java/com/accountbook/dto/category/CategoryDto.java
  src/main/java/com/accountbook/dto/category/CategoryRequest.java
  src/main/java/com/accountbook/dto/user/UserRequest.java
  src/main/java/com/accountbook/service/CategoryService.java
  src/main/java/com/accountbook/service/UserService.java
  src/test/java/com/accountbook/AccountBookApplicationTests.java
Labels: DONGGUN

#11 DONGGUN
  src/main/java/com/accountbook/AccountBookApplication.java
  src/main/java/com/accountbook/api/CategoryApiController.java
  src/main/java/com/accountbook/api/UserApiController.java
  src/main/java/com/accountbook/domain/entity/Category.java
  src/main/java/com/accountbook/domain/entity/ComCategory.java
  src/main/java/com/accountbook/domain/entity/User.java
  src/main/java/com/accountbook/domain/repository/category/CategoryRepository.java
  src/main/java/com/accountbook/domain/repository/category/ComCategoryRepository.java
  src/main/java/com/accountbook/domain/repository/user/UserRepository.java
  src/main/java/com/accountbook/domain/repository/user/UserRepositoryCustomImpl.java
  src/main/java/com/accountbook/dto/user/UserRequest.java
  src/main/java/com/accountbook/exception/handler/ControllerExceptionHandler.java
  src/main/java/com/accountbook/service/CategoryService.java
  src/main/java/com/accountbook/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/accountbook/AccountBookApplicationTests.java
  src/test/java/com/accountbook/service/CategoryServiceTest.java
  src/test/java/com/accountbook/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: DONGGUN

#12 EcoEvent 서비스 개발
  src/main/java/com/accountbook/api/EcoEventApiController.java
  src/main/java/com/accountbook/domain/entity/Budget.java
  src/main/java/com/accountbook/domain/entity/EcoEvent.java
  src/main/java/com/accountbook/domain/repository/BudgetRepository.java
  src/main/java/com/accountbook/domain/repository/EcoEventRepository.java
  src/main/java/com/accountbook/domain/repository/budget/BudgetRepository.java
  src/main/java/com/accountbook/domain/repository/budget/BudgetRepositoryCustom.java
  src/main/java/com/accountbook/domain/repository/budget/BudgetRepositoryCustomImpl.java
  src/main/java/com/accountbook/domain/repository/ecoEvent/EcoEventRepository.java
  src/main/java/com/accountbook/domain/repository/ecoEvent/EcoEventRepositoryCustom.java
  src/main/java/com/accountbook/domain/repository/ecoEvent/EcoEventRepositoryCustomImpl.java
  src/main/java/com/accountbook/dto/Budget/BudgetRequest.java
  src/main/java/com/accountbook/dto/EcoEvent/EcoEventRequest.java
  src/main/java/com/accountbook/service/BudgetService.java
  src/main/java/com/accountbook/service/EcoEventService.java
  src/test/java/com/accountbook/service/BudgetServiceTest.java
  src/test/java/com/accountbook/service/EcoEventServiceTest.java
Labels: SOOMIN
