Repository charmdong/account-book, pull requests merged in 2021-12, with the labels that each got.

#14 뭔가 추가되고 삭제됨
  src/main/java/com/accountbook/domain/repository/category/CategoryRepository.java
  src/main/java/com/accountbook/domain/repository/category/CategoryRepositoryCustom.java
  src/main/java/com/accountbook/domain/repository/category/CategoryRepositoryCustomImpl.java
  src/main/java/com/accountbook/exception/category/CategoryException.java
  src/main/java/com/accountbook/exception/category/CategoryNotDeletedException.java
  src/main/java/com/accountbook/exception/handler/CategoryExceptionHandler.java
  src/main/java/com/accountbook/exception/handler/CommonExceptionHandler.java
  src/main/java/com/accountbook/exception/handler/UserExceptionHandler.java
  src/main/java/com/accountbook/service/CategoryService.java
  src/main/java/com/accountbook/service/UserService.java
  src/test/java/com/accountbook/AccountBookApplicationTests.java
  src/test/java/com/accountbook/service/CategoryServiceTest.java
  src/test/java/com/accountbook/service/UserServiceTest.java
Labels: DONGGUN

#15 Update, Delete 서비스 수정, DTO Validation 변경
  build.gradle
  src/main/java/com/accountbook/api/BudgetApiController.java
  src/main/java/com/accountbook/api/EcoEventApiController.java
  src/main/java/com/accountbook/dto/Budget/BudgetRequest.java
  src/main/java/com/accountbook/service/BudgetService.java
  src/main/java/com/accountbook/service/EcoEventService.java
  src/test/java/com/accountbook/service/BudgetServiceTest.java
Labels: SOOMIN

#16 accout exception 처리
  src/main/java/com/accountbook/exception/account/AccountDeleteException.java
  src/main/java/com/accountbook/exception/account/AccountExceptionCode.java
  src/main/java/com/accountbook/exception/account/AccountNotExistedException.java
  src/main/java/com/accountbook/exception/account/AccountRegistException.java
  src/main/java/com/accountbook/exception/account/AccountUpdateException.java
  src/main/java/com/accountbook/exception/common/CommonExceptionHandler.java
  src/main/java/com/accountbook/service/AssetService.java
  src/main/resources/application.yml
Labels: MINGEON

#17 Donggun Pull Request
  .DS_Store
  src/main/java/com/accountbook/domain/repository/category/CategoryRepository.java
  src/main/java/com/accountbook/exception/category/CategoryExceptionCode.java
  src/main/java/com/accountbook/exception/category/CategoryExceptionHandler.java
  src/main/java/com/accountbook/exception/user/UserExceptionHandler.java
  src/main/java/com/accountbook/service/CategoryService.java
  src/main/java/com/accountbook/service/UserService.java
Labels: DONGGUN

#19 2021.12.12 [Exception 추가]
  src/main/java/com/accountbook/api/BudgetApiController.java
  src/main/java/com/accountbook/api/EcoEventApiController.java
  src/main/java/com/accountbook/exception/budget/BudgetExceptionCode.java
  src/main/java/com/accountbook/exception/budget/BudgetExceptionHandler.java
  src/main/java/com/accountbook/exception/budget/BudgetUpdateException.java
  src/main/java/com/accountbook/exception/budget/RelatedCategoryNotFoundException.java
  src/main/java/com/accountbook/exception/ecoEvent/EcoEventExceptionCode.java
  src/main/java/com/accountbook/exception/ecoEvent/EcoEventExceptionHandler.java
  src/main/java/com/accountbook/exception/ecoEvent/EcoEventUpdateException.java
  src/main/java/com/accountbook/exception/ecoEvent/RelatedCategoryNotFoundException.java
  src/main/java/com/accountbook/service/BudgetService.java
  src/main/java/com/accountbook/service/EcoEventService.java
Labels: SOOMIN

#21 Exception
  src/main/java/com/accountbook/api/CategoryApiController.java
  src/main/java/com/accountbook/api/UserApiController.java
  src/main/java/com/accountbook/domain/entity/Category.java
  src/main/java/com/accountbook/exception/category/CategoryException.java
  src/main/java/com/accountbook/exception/category/CategoryExceptionCode.java
  src/main/java/com/accountbook/exception/category/CategoryExceptionHandler.java
  src/main/java/com/accountbook/exception/category/CategoryNotDeletedException.java
  src/main/java/com/accountbook/exception/category/CategoryNotFoundException.java
  src/main/java/com/accountbook/exception/category/DeleteCategoryException.java
  src/main/java/com/accountbook/exception/category/InsertCategoryException.java
  src/main/java/com/accountbook/exception/category/UpdateCategoryException.java
  src/main/java/com/accountbook/exception/common/CommonException.java
  src/main/java/com/accountbook/exception/common/CommonExceptionCode.java
  src/main/java/com/accountbook/exception/common/CommonExceptionHandler.java
  src/main/java/com/accountbook/exception/user/DeleteUserException.java
  src/main/java/com/accountbook/exception/user/InsertUserException.java
  src/main/java/com/accountbook/exception/user/UserException.java
  src/main/java/com/accountbook/exception/user/UserExceptionCode.java
  src/main/java/com/accountbook/exception/user/UserExceptionHandler.java
  src/main/java/com/accountbook/exception/user/UserNotFoundException.java
  src/main/java/com/accountbook/service/CategoryService.java
  src/main/java/com/accountbook/service/UserService.java
Labels: DONGGUN

#22 Mg asset
  src/main/java/com/accountbook/api/AssetApiController.java
  src/main/java/com/accountbook/exception/account/AccountDeleteException.java
  src/main/java/com/accountbook/exception/account/AccountExceptionCode.java
  src/main/java/com/accountbook/exception/account/AccountNotExistedException.java
  src/main/java/com/accountbook/exception/account/AccountRegistException.java
  src/main/java/com/accountbook/exception/account/AccountUpdateException.java
  src/main/java/com/accountbook/exception/account/AssetDeleteException.java
  src/main/java/com/accountbook/exception/account/AssetException.java
  src/main/java/com/accountbook/exception/account/AssetExceptionCode.java
  src/main/java/com/accountbook/exception/account/AssetExceptionHandler.java
  src/main/java/com/accountbook/exception/account/AssetNotFoundException.java
  src/main/java/com/accountbook/exception/account/AssetRegistException.java
  src/main/java/com/accountbook/exception/account/AssetUpdateException.java
  src/main/java/com/accountbook/service/AssetService.java
  src/test/java/com/accountbook/service/AssetServiceTest.java
Labels: MINGEON
